In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=sns.load_dataset('iris')


In [3]:
X=df.drop('species',axis=1)
y=df.species

In [4]:
from  sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=104)

In [5]:
xtest=np.array(X_test)

In [6]:
xtrain=np.array(X_train)

In [7]:
from sklearn.metrics import classification_report,confusion_matrix 

In [8]:
y=[(xtrain-xtest[i])**2 for i in range(45)] 
c=np.zeros((45,105))
for i in range(45):
    for j in range(105):
        c[i][j]=np.array([np.sqrt(sum(y[i][j]))])
ind=[c[i].argmin() for i in range(45)]
predict = y_train.iloc[ind]

In [9]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        20
  versicolor       1.00      1.00      1.00        17
   virginica       1.00      1.00      1.00         8

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [10]:
print(confusion_matrix(y_test,predict))

[[20  0  0]
 [ 0 17  0]
 [ 0  0  8]]
